In [1]:
import numpy as np

In [2]:
a = np.arange(32).reshape(8,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
b = a.ravel()

In [9]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [10]:
b[5]

5

In [12]:
b[5:8] = 0

In [13]:
b

array([ 0,  1,  2,  3,  4,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [15]:
a.ndim

2

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [16]:
a[1]

array([4, 0, 0, 0])

In [18]:
a[5,3]

23

In [19]:
x = [1,2,3,4,5,6]
x[1:3]  = 4

TypeError: can only assign an iterable

In [20]:
a[:,0:2] = 3

In [21]:
a

array([[ 3,  3,  2,  3],
       [ 3,  3,  0,  0],
       [ 3,  3, 10, 11],
       [ 3,  3, 14, 15],
       [ 3,  3, 18, 19],
       [ 3,  3, 22, 23],
       [ 3,  3, 26, 27],
       [ 3,  3, 30, 31]])

In [ ]:
# Note
# An important first distinction from lists is that array slices are views on the original array.
# This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [23]:
a

array([[ 3,  3,  2,  3],
       [ 3,  3,  0,  0],
       [ 3,  3, 10, 11],
       [ 3,  3, 14, 15],
       [ 3,  3, 18, 19],
       [ 3,  3, 22, 23],
       [ 3,  3, 26, 27],
       [ 3,  3, 30, 31]])

In [25]:
a_slice = a[0:4,2:3]
a_slice
a_slice[:] = 77

In [26]:
a

array([[ 3,  3, 77,  3],
       [ 3,  3, 77,  0],
       [ 3,  3, 77, 11],
       [ 3,  3, 77, 15],
       [ 3,  3, 18, 19],
       [ 3,  3, 22, 23],
       [ 3,  3, 26, 27],
       [ 3,  3, 30, 31]])

In [ ]:
# if you dont want to change original one then coppy the slice into new varible 

In [27]:
x = a[0:3:,2:4].copy()

In [28]:
x[0,0] = 44

In [29]:
x

array([[44,  3],
       [77,  0],
       [77, 11]])

In [30]:
a

array([[ 3,  3, 77,  3],
       [ 3,  3, 77,  0],
       [ 3,  3, 77, 11],
       [ 3,  3, 77, 15],
       [ 3,  3, 18, 19],
       [ 3,  3, 22, 23],
       [ 3,  3, 26, 27],
       [ 3,  3, 30, 31]])

In [ ]:
# indexing & Slice 3d Array


In [31]:
q = np.arange(20).reshape(2,2,5)

In [32]:
q

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [33]:
q[0,1,2]

7

In [34]:
q[1,0:2,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
q[1,0:2,:] = 44

In [36]:
q

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[44, 44, 44, 44, 44],
        [44, 44, 44, 44, 44]]])

In [38]:
w = q[1,0:2,:]

In [39]:
w[0:2,1:4]  = 55

In [40]:
q

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[44, 55, 55, 55, 44],
        [44, 55, 55, 55, 44]]])

In [41]:
# indexing and slicing together
z = np.arange(20).reshape(4,5)

In [42]:
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
z[1,1:3] 

array([6, 7])

In [ ]:
z[1,1:3] = 4

In [44]:
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# Boolean indexing

In [81]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape(7, 4)

In [77]:
names

array([1, 2, 1, 4, 1, 7])

In [78]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [80]:
names == 'Bob'

array([ True, False,  True, False,  True, False])

In [49]:
names[names == 'Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [51]:
data[names=='Will']

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [52]:
# &, |    -----> and / or
mul_cond = (names == 'Bob') | (names == 'Will')   
data[mul_cond]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# Note
# Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.

In [53]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
# Fancy indexing


In [54]:
s = np.arange(25).reshape(5,5)

In [55]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
s[[2,3,4]]  # passing list of rows

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
s[[2,-3,4,-1]] 

array([[10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24]])

In [58]:
s[[2,-3,4,-1]]  = 23

In [59]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [23, 23, 23, 23, 23],
       [15, 16, 17, 18, 19],
       [23, 23, 23, 23, 23]])

In [60]:
d = s[[2,-3,4,-1]]

In [61]:
d

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [62]:
d[0:2,2:3]  = 21

In [63]:
d

array([[23, 23, 21, 23, 23],
       [23, 23, 21, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [64]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [23, 23, 23, 23, 23],
       [15, 16, 17, 18, 19],
       [23, 23, 23, 23, 23]])

In [ ]:
# Note
# Fancy indexing copy to new varible instead of view as above concepts

In [65]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [23, 23, 23, 23, 23],
       [15, 16, 17, 18, 19],
       [23, 23, 23, 23, 23]])

In [70]:
s[[1,2,3],[2,4,1]]   # row list and column list 

array([ 7, 23, 16])

C:\Users\musha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [ 5,  6,  7,  8,  9]])

In [ ]:
# np.ix_ function, which converts two 1D integer arrays to an indexer that selects the square region:
# Using ix_ one can quickly construct index arrays that will index the 
# cross product. a[np.ix_([1,3],[2,5])] returns the array [[a[1,2] a[1,5]], [a[3,2] a[3,5]]].


In [71]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [23, 23, 23, 23, 23],
       [15, 16, 17, 18, 19],
       [23, 23, 23, 23, 23]])

In [72]:
s[np.ix_([1,2,3],[2,4,1])]    # (1,2),(1,4),(1,1) and so on

array([[ 7,  9,  6],
       [23, 23, 23],
       [17, 19, 16]])

In [ ]:

# Note
# Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.