In [ ]:
import numpy as np

# Numpy
# Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# Arrays
# A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
# ways to create numpy arrays

In [ ]:
# scalars or 0D array
# np.array(23).ndim       

In [3]:
import numpy as np

In [10]:
ar1 = np.array([1, 2, 3, 4])
ar1




ar2 = np.array([[1, 2], [3, 4]])





ar3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# np.array([127, 128, 129], dtype=np.int8) 
# print(ar1)
# print(ar2)
# print(ar3.shape)

# making custom dim array
# arr = np.array([1, 2, 3, 4], ndmin=5)
# print(arr)
# print('number of dimensions :', arr.ndim)

In [12]:
ar3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# Builtin Methods to create array
# NumPy has over 40 built-in functions for creating arrays 
# these 40 divided into 3 categories
#        1d
#        2d
#        nd 


In [ ]:
# 1D array creation methods we discuess only famous one
#      numpy.linspace ---->will create arrays with a specified number of elements,
#             and spaced equally between the specified beginning and end values.
#             also include stope value
#      numpy.arange  ----> creates arrays with regularly incrementing values.not include stope value

In [15]:
a = np.linspace(1,10,5)

In [16]:
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:


b = np.arange(1,10,7)
b.ndim

1

In [30]:
# 2D array creation methods,  we discuess only famous one
# np.eye(n, m) -----> defines a 2D identity matrix
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#  ND array creation methods,  we discuess only famous one
#      numpy.ones  ----> will create an array filled with 0 values with the specified shape. 
#      numpy.zeros ----> will create an array filled with 1 values
#        np.full()  ----> fill with specific value
#      random ---->   The random method of the result of default_rng will create an array filled with
#                     random values between 0 and 1. It is included with the numpy.random library. 
#                     Below, two arrays are created with shapes (2,3) and (2,3,2), respectively. 
#                     The seed is set to 42 so you can reproduce these pseudorandom numbers:

# from numpy.random import default_rng
# default_rng(42).random((2,3))

In [51]:
# a = np.zeros((3,3))   # Create an array of all zeros
# print(a)              # Prints "[[ 0.  0.]
#                       #          [ 0.  0.]]"

# b = np.ones((3,4))    # Create an array of all ones
# print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2,2), 2)  # Create a constant array
print(c)   

[[[2 2]
  [2 2]]

 [[2 2]
  [2 2]]]


In [46]:
print(c.shape)

(5, 5)


In [42]:
c[0] = 7

In [43]:
c

array([[7, 7, 7, 7, 7],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [52]:
# type({1,2,3,4,5,5})  arry from set
np.array((1,2,3,4,5))



array([1, 2, 3, 4, 5])

In [56]:
# type((1,2,3,4,5,5))  #arry from tuple
np.array((1.6,2,3,4,5)).dtype

dtype('float64')

In [ ]:
# type({'a':1,'b':2,'c':3})
# np.array({'a':1,'b':2,'c':3})

In [ ]:
# Numpy Data types

# integer
# boolean
# unsigned integer
# float
# datetime
# string



In [ ]:

# arr = np.array([1, 2, 3, 'a'])

# print(arr)
# print(arr.dtype)

In [57]:
# Numpy Data Types
arr = np.array(['apple', 'banana', 'cherryc',])
arr.dtype

dtype('<U7')

In [59]:
# change datatype
# astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
a = np.array((1,2,3,4,5))
a.dtype

dtype('int32')

In [60]:
a.astype('f')

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
# Operations between Arrays and Scalars
# note--->Any arithmetic operations between equal-size arrays applies the operation elementwise:
# / + -  * % **    arthematic operatiom

In [61]:
a = np.arange(4).reshape(2,2)
b = np.arange(4).reshape(2,2)

In [62]:
print(a)
b

[[0 1]
 [2 3]]


array([[0, 1],
       [2, 3]])

In [66]:
a ** b

array([[ 1,  1],
       [ 4, 27]], dtype=int32)

In [67]:
a

array([[0, 1],
       [2, 3]])

In [72]:
# some useful function
# type(a)
# a.ndim
# a.shape
# a.itemsize #length of one element in bytes
a.size #total # of elements


4